var items= {
    "login": "millesky87",
    "id": 8504477,
    "avatar_url": "https://avatars.githubusercontent.com/u/8504477?v=2",
    "gravatar_id": "477ff7e2d0d5033eb368ad3200efc790",
    "url": "https://api.github.com/users/millesky87",
    "html_url": "https://github.com/millesky87",
    "followers_url": "https://api.github.com/users/millesky87/followers",
    "following_url": "https://api.github.com/users/millesky87/following{/other_user}",
    "gists_url": "https://api.github.com/users/millesky87/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/millesky87/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/millesky87/subscriptions",
    "organizations_url": "https://api.github.com/users/millesky87/orgs",
    "repos_url": "https://api.github.com/users/millesky87/repos",
    "events_url": "https://api.github.com/users/millesky87/events{/privacy}",
    "received_events_url": "https://api.github.com/users/millesky87/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Skylar Miller",
    "company": "",
    "blog": "",
    "location": "Greenville Sc",
    "email": "skyheamillz@gmail.com",
    "js_avatar":"https://avatars2.githubusercontent.com/u/8293064?v=2&s=84",
    "hireable": false,
    "bio": null,
    "public_repos": 7,
    "public_gists": 0,
    "followers": 1,
    "following": 0,
    "created_at": "2014-08-20T15:45:09Z",
    "updated_at": "2014-09-10T07:10:46Z"
  }
